@echo off
javac AboutUs.java
javac AdminPage.java
javac CreateUsers.java
javac DeleteLoginRecord.java
javac DeleteUsers.java
javac G18m1Record.java
javac G18m1WONGTestMain.java
javac G18M4APPOINTMENT.java
javac G18M4MAIN.java
javac G18M4TESTMAIN.java
javac Login.java
javac LoginRecord.java
javac LoginTest.java
javac User.java
javac Userpage.java
